//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Guests = new HashSet<Guest>();
        }
    
        public int BookingId { get; set; }
        public int EnquiryId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int AgentId { get; set; }
        public Nullable<byte> FlightOption { get; set; }
        public string BookingCode { get; set; }
        public int DestinationId { get; set; }
        public int PackageId { get; set; }
        public string NoOfDay { get; set; }
        public System.DateTime ArivalDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string NoOfPerson { get; set; }
        public decimal Rate { get; set; }
        public decimal TotalAmount { get; set; }
        public byte BookingStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string NoOfRoom { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Enquiry Enquiry { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guests { get; set; }
        public virtual Package Package { get; set; }
    }
}
