//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enquiry()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int EnquiryId { get; set; }
        public int DestinationId { get; set; }
        public int PackageId { get; set; }
        public System.DateTime TravelPlanDate { get; set; }
        public byte FlightOption { get; set; }
        public Nullable<int> NoOfRoom { get; set; }
        public Nullable<byte> MealPlan { get; set; }
        public Nullable<int> HotelCategoryId { get; set; }
        public byte Title { get; set; }
        public string PrimaryGuestName { get; set; }
        public string MobileNo { get; set; }
        public int NoOfPerson { get; set; }
        public byte EnquiryStatus { get; set; }
        public Nullable<decimal> AmountQuoted { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string EnquiryCode { get; set; }
        public int GuestId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual HotelCategory HotelCategory { get; set; }
        public virtual Package Package { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
    }
}
