//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int GuestId { get; set; }
        public string GuestName { get; set; }
        public string Title { get; set; }
        public string Age { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> IDTypeId { get; set; }
        public string IDNo { get; set; }
        public string GSTNo { get; set; }
        public int BookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual IDType IDType { get; set; }
    }
}
